### PR TITLE
ctrlf-search-style-is-sticky - persist modified search style in buffer

### PR DESCRIPTION
**Pull request by rileyrg**
-------

### CODE REVIEW

**Comment by rileyrg** [comment]
Discussion start: https://github.com/raxod502/ctrlf/issues/83#issuecomment-816975795

**Comment by rileyrg** [comment]
I'm unfamiliar with circleci but will address the check errors in the next couple of days.

**Review by raxod502 — COMMENTED** [review]
If I'm understanding correctly the discussion in https://github.com/raxod502/ctrlf/issues/83#issuecomment-816879304, the main issue is that when using `C-s C-s` to resume a search, the style is reset to the default, rather than being the same as previous.

Given that, might it be more elegant to add a special case to `C-s C-s` specifically that will restore the previous search style? Rather than changing the overall default for all searches in the buffer?

**Comment by raxod502** [comment]
You can run the linters locally with `make lint`, by the way.

**Comment by rileyrg** [comment]
> If I'm understanding correctly the discussion in [#83 (comment)](https://github.com/raxod502/ctrlf/issues/83#issuecomment-816879304), the main issue is that when using `C-s C-s` to resume a search, the style is reset to the default, rather than being the same as previous.
> 
> Given that, might it be more elegant to add a special case to `C-s C-s` specifically that will restore the previous search style? Rather than changing the overall default for all searches in the buffer?

Possibly. Personally, when I change the search style I like it to stick for that buffer and that why I put in a sticky custom which defaults to false to keep the original behaviour.  I'm a bit of a PR beginner so go gentle.

I did the "make lint" btw - 80 chars per line when quoting elisp vars is quite a challenge ;)

**Comment by raxod502** [comment]
Well, I certainly don't have any objection to adding an option to make the search style persistent per buffer. Just wanted to suggest an alternative if that was a better fit to the problem :)

**Comment by rileyrg** [comment]
> Well, I certainly don't have any objection to adding an option to make the search style persistent per buffer. Just wanted to suggest an alternative if that was a better fit to the problem :)

;) I like your ctrlf very much. But I really can't imagine a case where I personally would not want to sticky the search style change in the buffer.  Yes, my PR is only for the default forward and backwards and not "alternate" and I think that works.

**Comment by haji-ali** [comment]
The alternative search should still be handled because if you start an alternative search, then change the style with `M-s s` for example, you shouldn't change the default search style I think.

**Comment by rileyrg** [comment]
> The alternative search should still be handled because if you start an alternative search, then change the style with `M-s s` for example, you shouldn't change the default search style I think.

Oh I see.  I've never used alternate I must admit, I find that's "too many chunks l" used up 😉 I'll have a peek. Thanks.

**Comment by haji-ali** [comment]
First, I suggest the new option be called `ctrlf-preserve-search-style` instead of `ctrlf-search-style-is-sticky`.

Also, I think there's an easier way to implement this feature that would also deal with the alternative style and provide a simple way to override the behavior as @raxod502 suggested. Simply change the lines

https://github.com/raxod502/ctrlf/blob/45026a8655fb170004959f83b984589224cc156e/ctrlf.el#L1080-L1081

and 

https://github.com/raxod502/ctrlf/blob/45026a8655fb170004959f83b984589224cc156e/ctrlf.el#L1117-L1118

to 
```elisp
(unless (or ctrlf--active-p ctrlf-preserve-search-style)
      (setq preserve nil))
```

Also, for buffer-local search style, you would need to make the variable `ctrlf--style` local by calling.
```elisp
(make-local-variable `ctrlf--style)
```
after defining `ctrlf--style` on line 332.

This way, if the new `ctrlf-preserve-search-style` is non-nil then unless `C-u` is pressed before `C-s`, the search style is not reset.

**Comment by rileyrg** [comment]
I'll withdraw the pr.  Feel free to submit.  I don't have time for next days. Thanks for the feedback.

**Comment by rileyrg** [comment]
Just realised that probably sounded a bit offish - wasn't intended, I was in a rush. I'll try and find some time soon.

**Comment by rileyrg** [comment]
issues with alternate search - need to think some more on this. revisit another day.

**Comment by raxod502** [comment]
Sounds good! Definitely no rush :)

**Comment by rileyrg** [comment]
I'm going to leave this for now as the whole alternative search makes it a bit of churn and my elisp isn't up to it (it simply calls same functions with a different style) . I just know altered search type should stick for repeat search😂  I've never used alternative search and the ease of altering search anyway makes me wonder if it's not over kill anyway. I'll go  back to fuzzy regexp as default and then none of it matters for my use anyway.

**Pull request closed without merging**
